package main

import (
	"fmt"
	"log/slog"
	"time"

	"github.com/thepixelabs/kubecat/internal/ai"
	"github.com/thepixelabs/kubecat/internal/audit"
	"github.com/thepixelabs/kubecat/internal/config"
)

// AIStreamToken is emitted on the "ai:token" event for each incremental token.
type AIStreamToken struct {
	// ConversationID scopes tokens to the originating conversation so the
	// frontend can route them to the correct message.
	ConversationID string `json:"conversationId"`
	// Token is the incremental text fragment.
	Token string `json:"token"`
}

// AIStreamDone is emitted on "ai:done" when streaming is complete.
type AIStreamDone struct {
	// ConversationID matches the one passed to AIQueryStream.
	ConversationID string `json:"conversationId"`
	// FullResponse is the complete concatenated response.
	FullResponse string `json:"fullResponse"`
	// DurationMs is the total wall-clock time in milliseconds.
	DurationMs int64 `json:"durationMs"`
}

// AIStreamError is emitted on "ai:error" when streaming fails.
type AIStreamError struct {
	ConversationID string `json:"conversationId"`
	Error          string `json:"error"`
}

// AIQueryStream starts a streaming AI query.  Tokens are delivered to the
// frontend via "ai:token" events and a final "ai:done" event.  The method
// returns immediately; all delivery happens in a background goroutine.
//
// conversationID should be a UUID generated by the frontend to correlate
// all events belonging to the same conversation turn.
func (a *App) AIQueryStream(query string, conversationID string, providerID string, modelID string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	if !cfg.Kubecat.AI.Enabled {
		return fmt.Errorf("AI features are not enabled. Please enable them in Settings.")
	}

	selectedProvider := providerID
	if selectedProvider == "" {
		selectedProvider = cfg.Kubecat.AI.SelectedProvider
	}
	if selectedProvider == "" {
		return fmt.Errorf("no AI provider selected")
	}

	selectedModel := modelID
	if selectedModel == "" {
		selectedModel = cfg.Kubecat.AI.SelectedModel
	}

	providerConfig, ok := cfg.Kubecat.AI.Providers[selectedProvider]
	if !ok || !providerConfig.Enabled {
		return fmt.Errorf("AI provider %q is not enabled or configured", selectedProvider)
	}

	providerCfg := ai.ProviderConfig{
		Model:    selectedModel,
		APIKey:   providerConfig.APIKey,
		Endpoint: providerConfig.Endpoint,
		Timeout:  120 * time.Second,
	}

	var provider ai.Provider
	switch selectedProvider {
	case "openai", "litellm":
		provider = ai.NewOpenAIProvider(providerCfg)
	case "anthropic":
		provider = ai.NewAnthropicProvider(providerCfg)
	case "google":
		provider = ai.NewGoogleProvider(providerCfg)
	case "ollama":
		provider = ai.NewOllamaProvider(providerCfg)
	default:
		return fmt.Errorf("unknown AI provider: %s", selectedProvider)
	}

	sanitizedQuery := query
	if ai.IsCloudProvider(selectedProvider) {
		sanitizedQuery = ai.SanitizeForCloud(query)
	}

	audit.LogAIQuery(selectedProvider, a.nexus.Clusters.ActiveContext(), "", sanitizedQuery)

	// Launch the stream in a background goroutine so this method returns
	// immediately to the frontend.
	go func() {
		defer func() { _ = provider.Close() }()

		start := time.Now()

		if !provider.Available(a.ctx) {
			a.emitter.Emit("ai:error", AIStreamError{
				ConversationID: conversationID,
				Error:          "AI provider is not available",
			})
			return
		}

		ch, err := provider.StreamQuery(a.ctx, sanitizedQuery)
		if err != nil {
			slog.Warn("AIQueryStream: StreamQuery failed",
				slog.String("provider", selectedProvider),
				slog.Any("error", err))
			a.emitter.Emit("ai:error", AIStreamError{
				ConversationID: conversationID,
				Error:          fmt.Sprintf("stream query failed: %s", err.Error()),
			})
			return
		}

		var fullResponse string
		for token := range ch {
			fullResponse += token
			a.emitter.Emit("ai:token", AIStreamToken{
				ConversationID: conversationID,
				Token:          token,
			})
		}

		a.emitter.Emit("ai:done", AIStreamDone{
			ConversationID: conversationID,
			FullResponse:   fullResponse,
			DurationMs:     time.Since(start).Milliseconds(),
		})

		slog.Info("AIQueryStream: completed",
			slog.String("provider", selectedProvider),
			slog.String("conversationId", conversationID),
			slog.Int("responseBytes", len(fullResponse)),
			slog.Duration("duration", time.Since(start)),
		)
	}()

	return nil
}
