// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {network} from '../models';
import {context} from '../models';
import {client} from '../models';
import {config} from '../models';
import {cost} from '../models';
import {rbac} from '../models';
import {ai} from '../models';

export function AIAgentQuery(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AIAnalyzeResource(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AIQuery(arg1:string):Promise<string>;

export function AIQueryStream(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AIQueryWithContext(arg1:string,arg2:Array<main.AIContextItem>,arg3:string,arg4:string,arg5:Array<main.ConversationMessage>):Promise<string>;

export function AnalyzeNetworkPolicies(arg1:string,arg2:string):Promise<network.NetworkGraph>;

export function AnalyzeResource(arg1:string,arg2:string,arg3:string):Promise<Array<main.AnalyzerIssue>>;

export function ApplyResourceToCluster(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<main.ApplyResult>;

export function ApproveAgentAction(arg1:string,arg2:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ComputeDiff(arg1:main.DiffRequest):Promise<main.DiffResult>;

export function Connect(arg1:string):Promise<void>;

export function CreatePortForward(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.PortForwardInfo>;

export function DeleteResource(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DetectCostBackend():Promise<string>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string):Promise<string>;

export function ExecuteTool(arg1:context.Context,arg2:string,arg3:Record<string, string>):Promise<string>;

export function FetchProviderModels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GenerateDiffReport(arg1:main.DiffResult,arg2:string):Promise<main.DiffReport>;

export function GetAISettings():Promise<main.AISettings>;

export function GetActiveContext():Promise<string>;

export function GetAlertSettings():Promise<main.AlertSettings>;

export function GetAppVersion():Promise<string>;

export function GetAvailableProviders():Promise<Array<main.ProviderInfo>>;

export function GetBufferedLogs():Promise<Array<string>>;

export function GetBufferedWorkloadLogs():Promise<Array<main.LogLine>>;

export function GetClusterEdges(arg1:string):Promise<Array<main.ClusterEdge>>;

export function GetClusterInfo():Promise<client.ClusterInfo>;

export function GetContexts():Promise<Array<string>>;

export function GetCostSettings():Promise<config.CostConfig>;

export function GetGitOpsApplication(arg1:string,arg2:string,arg3:string):Promise<main.GitOpsApplicationInfo>;

export function GetGitOpsStatus():Promise<main.GitOpsStatusInfo>;

export function GetMCPStatus():Promise<Record<string, any>>;

export function GetMultiClusterHealth():Promise<Array<main.ClusterHealthInfo>>;

export function GetNamespaceCostSummary(arg1:string,arg2:string):Promise<cost.NamespaceCostSummary>;

export function GetNamespaceRBAC(arg1:string,arg2:string):Promise<rbac.RBACMatrix>;

export function GetNetworkPolicyYAML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetNodeAllocation():Promise<Array<main.NodeAllocationInfo>>;

export function GetRBACAnalysis():Promise<main.RBACSummary>;

export function GetResource(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetResourceFromContext(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetResourceFromSnapshot(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetResourceYAML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSecretData(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetSecurityIssues(arg1:string,arg2:string):Promise<Array<main.SecurityIssueInfo>>;

export function GetSecuritySummary(arg1:string):Promise<main.SecuritySummaryInfo>;

export function GetSnapshotDiff(arg1:string,arg2:string):Promise<main.SnapshotDiffResult>;

export function GetSnapshots(arg1:number):Promise<Array<main.SnapshotInfo>>;

export function GetSubjectPermissions(arg1:string,arg2:string,arg3:string):Promise<Array<main.RBACBinding>>;

export function GetTimelineEvents(arg1:main.TimelineFilter):Promise<Array<main.TimelineEvent>>;

export function GetWorkloadCost(arg1:string,arg2:string,arg3:string):Promise<cost.CostEstimate>;

export function IsConnected():Promise<boolean>;

export function IsTimelineAvailable():Promise<boolean>;

export function ListPortForwards():Promise<Array<main.PortForwardInfo>>;

export function ListResources(arg1:string,arg2:string):Promise<Array<main.ResourceInfo>>;

export function QuerySecurityAI(arg1:string):Promise<string>;

export function RefreshContexts():Promise<Array<string>>;

export function RejectAgentAction(arg1:string,arg2:string):Promise<void>;

export function RequestApproval(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>,arg6:ai.ToolCategory):Promise<ai.ApprovalDecision>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveAISettings(arg1:main.AISettings):Promise<void>;

export function SaveAlertSettings(arg1:main.AlertSettings):Promise<void>;

export function SaveCostSettings(arg1:config.CostConfig):Promise<void>;

export function ScanCluster(arg1:string):Promise<main.AnalyzerSummary>;

export function SearchAcrossClusters(arg1:string,arg2:string):Promise<Array<main.CrossClusterSearchResult>>;

export function SearchLogs(arg1:string):Promise<Array<main.LogMatchInfo>>;

export function StartLogStream(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function StartMCPServer():Promise<void>;

export function StartProactiveAlertMonitor(arg1:context.Context):Promise<void>;

export function StartResourceWatch(arg1:string,arg2:string):Promise<void>;

export function StartTerminal(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function StartWorkloadLogStream(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function StopAgentSession(arg1:string):Promise<void>;

export function StopAllResourceWatchers():Promise<void>;

export function StopLogStream():Promise<void>;

export function StopMCPServer():Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function StopResourceWatch(arg1:string):Promise<void>;

export function SyncGitOpsApplication(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TakeSnapshot():Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
