// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIAgentQuery(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AIAgentQuery'](arg1, arg2, arg3, arg4, arg5);
}

export function AIAnalyzeResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['AIAnalyzeResource'](arg1, arg2, arg3);
}

export function AIQuery(arg1) {
  return window['go']['main']['App']['AIQuery'](arg1);
}

export function AIQueryStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AIQueryStream'](arg1, arg2, arg3, arg4);
}

export function AIQueryWithContext(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AIQueryWithContext'](arg1, arg2, arg3, arg4, arg5);
}

export function AnalyzeNetworkPolicies(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeNetworkPolicies'](arg1, arg2);
}

export function AnalyzeResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeResource'](arg1, arg2, arg3);
}

export function ApplyResourceToCluster(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ApplyResourceToCluster'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ApproveAgentAction(arg1, arg2) {
  return window['go']['main']['App']['ApproveAgentAction'](arg1, arg2);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ComputeDiff(arg1) {
  return window['go']['main']['App']['ComputeDiff'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreatePortForward(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePortForward'](arg1, arg2, arg3, arg4);
}

export function DeleteResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteResource'](arg1, arg2, arg3);
}

export function DetectCostBackend() {
  return window['go']['main']['App']['DetectCostBackend']();
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function ExecuteTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteTool'](arg1, arg2, arg3);
}

export function FetchProviderModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2, arg3);
}

export function GenerateDiffReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateDiffReport'](arg1, arg2);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetActiveContext() {
  return window['go']['main']['App']['GetActiveContext']();
}

export function GetAlertSettings() {
  return window['go']['main']['App']['GetAlertSettings']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetBufferedLogs() {
  return window['go']['main']['App']['GetBufferedLogs']();
}

export function GetBufferedWorkloadLogs() {
  return window['go']['main']['App']['GetBufferedWorkloadLogs']();
}

export function GetClusterEdges(arg1) {
  return window['go']['main']['App']['GetClusterEdges'](arg1);
}

export function GetClusterInfo() {
  return window['go']['main']['App']['GetClusterInfo']();
}

export function GetContexts() {
  return window['go']['main']['App']['GetContexts']();
}

export function GetCostSettings() {
  return window['go']['main']['App']['GetCostSettings']();
}

export function GetGitOpsApplication(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGitOpsApplication'](arg1, arg2, arg3);
}

export function GetGitOpsStatus() {
  return window['go']['main']['App']['GetGitOpsStatus']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMultiClusterHealth() {
  return window['go']['main']['App']['GetMultiClusterHealth']();
}

export function GetNamespaceCostSummary(arg1, arg2) {
  return window['go']['main']['App']['GetNamespaceCostSummary'](arg1, arg2);
}

export function GetNamespaceRBAC(arg1, arg2) {
  return window['go']['main']['App']['GetNamespaceRBAC'](arg1, arg2);
}

export function GetNetworkPolicyYAML(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNetworkPolicyYAML'](arg1, arg2, arg3);
}

export function GetNodeAllocation() {
  return window['go']['main']['App']['GetNodeAllocation']();
}

export function GetRBACAnalysis() {
  return window['go']['main']['App']['GetRBACAnalysis']();
}

export function GetResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResource'](arg1, arg2, arg3);
}

export function GetResourceFromContext(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetResourceFromContext'](arg1, arg2, arg3, arg4);
}

export function GetResourceFromSnapshot(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetResourceFromSnapshot'](arg1, arg2, arg3, arg4, arg5);
}

export function GetResourceYAML(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResourceYAML'](arg1, arg2, arg3);
}

export function GetSecretData(arg1, arg2) {
  return window['go']['main']['App']['GetSecretData'](arg1, arg2);
}

export function GetSecurityIssues(arg1, arg2) {
  return window['go']['main']['App']['GetSecurityIssues'](arg1, arg2);
}

export function GetSecuritySummary(arg1) {
  return window['go']['main']['App']['GetSecuritySummary'](arg1);
}

export function GetSnapshotDiff(arg1, arg2) {
  return window['go']['main']['App']['GetSnapshotDiff'](arg1, arg2);
}

export function GetSnapshots(arg1) {
  return window['go']['main']['App']['GetSnapshots'](arg1);
}

export function GetSubjectPermissions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSubjectPermissions'](arg1, arg2, arg3);
}

export function GetTimelineEvents(arg1) {
  return window['go']['main']['App']['GetTimelineEvents'](arg1);
}

export function GetWorkloadCost(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWorkloadCost'](arg1, arg2, arg3);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsTimelineAvailable() {
  return window['go']['main']['App']['IsTimelineAvailable']();
}

export function ListPortForwards() {
  return window['go']['main']['App']['ListPortForwards']();
}

export function ListResources(arg1, arg2) {
  return window['go']['main']['App']['ListResources'](arg1, arg2);
}

export function QuerySecurityAI(arg1) {
  return window['go']['main']['App']['QuerySecurityAI'](arg1);
}

export function RefreshContexts() {
  return window['go']['main']['App']['RefreshContexts']();
}

export function RejectAgentAction(arg1, arg2) {
  return window['go']['main']['App']['RejectAgentAction'](arg1, arg2);
}

export function RequestApproval(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RequestApproval'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveAISettings(arg1) {
  return window['go']['main']['App']['SaveAISettings'](arg1);
}

export function SaveAlertSettings(arg1) {
  return window['go']['main']['App']['SaveAlertSettings'](arg1);
}

export function SaveCostSettings(arg1) {
  return window['go']['main']['App']['SaveCostSettings'](arg1);
}

export function ScanCluster(arg1) {
  return window['go']['main']['App']['ScanCluster'](arg1);
}

export function SearchAcrossClusters(arg1, arg2) {
  return window['go']['main']['App']['SearchAcrossClusters'](arg1, arg2);
}

export function SearchLogs(arg1) {
  return window['go']['main']['App']['SearchLogs'](arg1);
}

export function StartLogStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLogStream'](arg1, arg2, arg3, arg4);
}

export function StartMCPServer() {
  return window['go']['main']['App']['StartMCPServer']();
}

export function StartProactiveAlertMonitor(arg1) {
  return window['go']['main']['App']['StartProactiveAlertMonitor'](arg1);
}

export function StartResourceWatch(arg1, arg2) {
  return window['go']['main']['App']['StartResourceWatch'](arg1, arg2);
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3);
}

export function StartWorkloadLogStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartWorkloadLogStream'](arg1, arg2, arg3, arg4);
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}

export function StopAllResourceWatchers() {
  return window['go']['main']['App']['StopAllResourceWatchers']();
}

export function StopLogStream() {
  return window['go']['main']['App']['StopLogStream']();
}

export function StopMCPServer() {
  return window['go']['main']['App']['StopMCPServer']();
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function StopResourceWatch(arg1) {
  return window['go']['main']['App']['StopResourceWatch'](arg1);
}

export function SyncGitOpsApplication(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncGitOpsApplication'](arg1, arg2, arg3);
}

export function TakeSnapshot() {
  return window['go']['main']['App']['TakeSnapshot']();
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
